# Generated by Django 4.0.7 on 2022-09-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="auth_str",
            field=models.CharField(default="", max_length=100),
        ),
    ]
