# Generated by Django 4.0.7 on 2022-09-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_customuser_auth_str"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="auth_str",
            field=models.CharField(default="", max_length=256),
        ),
    ]
